// Provider and Supabase responses are mocked. No real payment/network requests.
const assert=(condition:unknown,message:string)=>{if(!condition)throw new Error(message);};
let handler:(request:Request)=>Promise<Response>;
const originalServe=Deno.serve;
Object.defineProperty(Deno,'serve',{value:(callback:typeof handler)=>{handler=callback;return {};},configurable:true});
Deno.env.set('PAYSTACK_SECRET_KEY','review-secret');Deno.env.set('SUPABASE_URL','https://review.supabase.test');Deno.env.set('SUPABASE_SERVICE_ROLE_KEY','review-service');
await import('../functions/paystack-webhook/index.ts');
Object.defineProperty(Deno,'serve',{value:originalServe,configurable:true});
const originalFetch=globalThis.fetch;
const body=JSON.stringify({event:'charge.success',data:{reference:'review-reference',amount:9900,status:'success'}});
const encoder=new TextEncoder();const key=await crypto.subtle.importKey('raw',encoder.encode('review-secret'),{name:'HMAC',hash:'SHA-512'},false,['sign']);
const bytes=await crypto.subtle.sign('HMAC',key,encoder.encode(body));const signature=Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('');
const request=(sig=signature)=>new Request('https://review.test/webhook',{method:'POST',headers:{'x-paystack-signature':sig},body});
Deno.test('invalid signature never activates',async()=>{let calls=0;globalThis.fetch=()=>{calls++;throw new Error('unexpected request');};try{assert((await handler(request('invalid'))).status===401,'must reject');assert(calls===0,'must not call provider/database');}finally{globalThis.fetch=originalFetch;}});
Deno.test('provider unavailable retries without granting premium',async()=>{let complete=0;globalThis.fetch=async(input)=>{if(String(input).includes('complete_payment'))complete++;return new Response('{}',{status:503});};try{assert((await handler(request())).status===503,'must request retry');assert(complete===0,'must not activate from webhook payload alone');}finally{globalThis.fetch=originalFetch;}});
Deno.test('verified KES transaction activates with converted amount',async()=>{let complete=0;globalThis.fetch=async(input,init)=>{if(String(input).includes('/transaction/verify/'))return Response.json({status:true,data:{status:'success',currency:'KES',reference:'review-reference',amount:9900,id:123}});if(String(input).includes('complete_payment')){complete++;const payload=JSON.parse(String(init?.body));assert(payload.p_paid_amount===99,'KES amount conversion');assert(payload.p_reference==='review-reference','reference binding');return Response.json('activated');}throw new Error('Unexpected request');};try{assert((await handler(request())).status===200,'valid webhook should succeed');assert(complete===1,'activate exactly once per handling');}finally{globalThis.fetch=originalFetch;}});
Deno.test('wrong currency cannot activate',async()=>{let complete=0;globalThis.fetch=async(input)=>{if(String(input).includes('/transaction/verify/'))return Response.json({status:true,data:{status:'success',currency:'USD',reference:'review-reference',amount:9900}});if(String(input).includes('complete_payment'))complete++;return Response.json('failed');};try{assert((await handler(request())).status===200,'record rejection');assert(complete===0,'foreign currency must not activate');}finally{globalThis.fetch=originalFetch;}});
Deno.test('database activation failure requests retry',async()=>{globalThis.fetch=async(input)=>String(input).includes('/transaction/verify/')?Response.json({status:true,data:{status:'success',currency:'KES',reference:'review-reference',amount:9900}}):Response.json({message:'Unavailable'},{status:500});try{assert((await handler(request())).status===500,'failed activation must be retried');}finally{globalThis.fetch=originalFetch;}});
